version: '3'

services:

    # Redis service for redis things.
    {{ cookiecutter.redis_hostname }}:
        image: redis
        ports:
            - "6379:6379"
        volumes:
            - {{ cookiecutter.redis_volume }}:/data

    # MySQL service for mysql things.
    {{ cookiecutter.mysql_hostname }}:
        image: redis
        environment:
            - MYSQL_ROOT_PASSWORD={{ cookiecutter.mysql_root_password }}
            - MYSQL_DATABASE={{ cookiecutter.mysql_database }}
            - MYSQL_USER={{ cookiecutter.mysql_user }}
            - MYSQL_PASSWORD={{ cookiecutter.mysql_password }}
        ports:
            - "3306:3306"
        volumes:
            - {{ cookiecutter.mysql_volume }}:/data

volumes:
    {{ cookiecutter.redis_volume }}:
    {{ cookiecutter.postgres_volume }}:
    {{ cookiecutter.mysql_volume }}:
