name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Thanks for reaching out with an issue!  Please feel free to take a crack at it with a PR if you want!'
        pr-message: 'Thanks for submitting your first PR!  We appreciate the help!  Please note that nothing will be merged unless testing passes!'
